# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Democracy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Democracy
  
  pod 'LetMeAuth-FcaebookSDK-ios', '~>2.0'
  pod 'AFNetworking', '~> 3.1'
  pod 'JSONKit', '~> 1.4'

  target 'DemocracyTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  

end
